import { useRef, useMemo, useEffect, useState, useCallback, memo } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";
import { LAND_MASK_B64, MASK_W, MASK_H } from "./land-mask";
import { DOT_STEP, DOTS_B64 } from "./land-dots";
import { latLngToVec3 } from "./geo";
import { ArcLayer } from "./ArcLayer";
import { PostcardFlightLayer, LandedCardStamp } from "./PostcardFlightLayer";
import type { ArcTarget, LiveCard } from "./types";

export interface DottedGlobeProps {
  /** Spacing between land dots in degrees (default: 1.1) */
  dotStep?: number;
  /** Globe radius (default: 2.5) */
  radius?: number;
  /** Land dot color (default: '#ede6db') */
  dotColor?: string;
  /** Land dot size multiplier (default: 0.45) */
  dotSize?: number;
  /** Water/ocean color (default: '#4a7fb5') */
  waterColor?: string;
  /** Water opacity (default: 0.12) */
  waterOpacity?: number;
  /** Postcard arc destinations */
  arcs?: ArcTarget[];
  /** Delay in seconds before arcs start animating (default: 0) */
  arcDelay?: number;
  /** Auto-rotation speed in rad/s (default: 0.1) */
  rotationSpeed?: number;
  /** Live postcard cards to animate flying toward the globe */
  liveCards?: LiveCard[];
}

// ---------------------------------------------------------------------------
// Mock postcard destinations (used when no arcs prop is provided)
// ---------------------------------------------------------------------------

const MOCK_ARCS: ArcTarget[] = [
  { id: "1", latitude: 35.6762, longitude: 139.6503 }, // Tokyo
  { id: "2", latitude: -33.8688, longitude: 151.2093 }, // Sydney
  { id: "3", latitude: 40.7128, longitude: -74.006 }, // New York
  { id: "4", latitude: -22.9068, longitude: -43.1729 }, // Rio de Janeiro
  { id: "5", latitude: 28.6139, longitude: 77.209 }, // New Delhi
  { id: "6", latitude: 48.8566, longitude: 2.3522 }, // Paris
  { id: "7", latitude: -1.2921, longitude: 36.8219 }, // Nairobi
  { id: "8", latitude: 55.7558, longitude: 37.6173 }, // Moscow
  { id: "9", latitude: 37.5665, longitude: 126.978 }, // Seoul
  { id: "10", latitude: -34.6037, longitude: -58.3816 }, // Buenos Aires
];

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEG = Math.PI / 180;

// ---------------------------------------------------------------------------
// Decode land mask once at module level (~1ms)
// ---------------------------------------------------------------------------

const LAND_MASK: Uint8Array = (() => {
  const bin = atob(LAND_MASK_B64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
})();

function sampleMask(lat: number, lng: number): boolean {
  const x = Math.floor(((lng + 180) / 360) * MASK_W) % MASK_W;
  const y = Math.max(0, Math.min(MASK_H - 1, Math.floor(((90 - lat) / 180) * MASK_H)));
  const idx = y * MASK_W + x;
  return (LAND_MASK[idx >> 3] & (1 << (idx & 7))) !== 0;
}

// ---------------------------------------------------------------------------
// Precalculated dot data (generated by scripts/generate-land-dots.ts)
// Stored as Int16 lat/lng pairs, decoded to xyz + scale at load time
// ---------------------------------------------------------------------------

interface LandData {
  positions: Float32Array;
  scales: Float32Array;
}

function scaleForLat(lat: number): number {
  if (lat < -65) return Math.max(0.3, (lat + 80) / 15);
  if (lat > 75) return Math.max(0.3, (90 - lat) / 15);
  return 1;
}

function decodePrecalcDots(radius: number): LandData {
  const bin = atob(DOTS_B64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  const packed = new Int16Array(bytes.buffer);

  const count = packed.length / 2;
  const positions = new Float32Array(count * 3);
  const scales = new Float32Array(count);

  for (let i = 0; i < count; i++) {
    const lat = packed[i * 2] / 100;
    const lng = packed[i * 2 + 1] / 100;
    const [x, y, z] = latLngToVec3(lat, lng, radius);
    positions[i * 3] = x;
    positions[i * 3 + 1] = y;
    positions[i * 3 + 2] = z;
    scales[i] = scaleForLat(lat);
  }

  return { positions, scales };
}

function computeLandDots(step: number, radius: number): LandData {
  // Use precalculated lat/lng data for default step
  if (step === DOT_STEP) return decodePrecalcDots(radius);

  // Fallback: compute at runtime for non-default step
  const positions: number[] = [];
  const scales: number[] = [];

  for (let lat = -80 + step / 2; lat < 90; lat += step) {
    const cosLat = Math.cos(lat * DEG);
    const lngStep = cosLat > 0.05 ? step / cosLat : 360;
    const scale = scaleForLat(lat);

    for (let lng = -180 + lngStep / 2; lng < 180; lng += lngStep) {
      if (sampleMask(lat, lng)) {
        const [x, y, z] = latLngToVec3(lat, lng, radius);
        positions.push(x, y, z);
        scales.push(scale);
      }
    }
  }

  return {
    positions: new Float32Array(positions),
    scales: new Float32Array(scales),
  };
}

// ---------------------------------------------------------------------------
// Land mask as a DataTexture (for the inner sphere shader)
// ---------------------------------------------------------------------------

const MASK_TEXTURE: THREE.DataTexture = (() => {
  const data = new Uint8Array(MASK_W * MASK_H * 4);
  for (let i = 0; i < MASK_W * MASK_H; i++) {
    const isLand = (LAND_MASK[i >> 3] & (1 << (i & 7))) !== 0;
    const v = isLand ? 255 : 0;
    data[i * 4] = v;
    data[i * 4 + 1] = v;
    data[i * 4 + 2] = v;
    data[i * 4 + 3] = 255;
  }
  const tex = new THREE.DataTexture(data, MASK_W, MASK_H, THREE.RGBAFormat);
  tex.needsUpdate = true;
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.wrapS = THREE.RepeatWrapping;
  return tex;
})();

// ---------------------------------------------------------------------------
// Shaders
// ---------------------------------------------------------------------------

const oceanSphereVertex = /* glsl */ `
  varying vec2 vUv;
  varying vec3 vViewPos;
  varying vec3 vNormal;

  void main() {
    vUv = uv;
    vNormal = normalize(normalMatrix * normal);
    vViewPos = (modelViewMatrix * vec4(position, 1.0)).xyz;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const oceanSphereFragment = /* glsl */ `
  precision highp float;
  uniform sampler2D uMask;
  uniform vec3 uWaterColor;
  uniform vec3 uLandColor;
  uniform float uWaterOpacity;
  uniform float uLandOpacity;
  varying vec2 vUv;
  varying vec3 vViewPos;
  varying vec3 vNormal;

  void main() {
    // Flip V (mask top-to-bottom, UVs bottom-to-top), mirror U, shift 0.5 to align with dot longitudes
    float land = texture2D(uMask, vec2(vUv.x, 1.0 - vUv.y)).r;

    // Water = blue, land = dark
    vec3 color = mix(uWaterColor, uLandColor, land);
    float opacity = mix(uWaterOpacity, uLandOpacity, land);

    // Fade backside
    vec3 viewDir = normalize(-vViewPos);
    float facing = dot(vNormal, viewDir);
    if (facing < 0.0) {
      opacity *= max(0.0, 1.0 + facing * 1.5);
    }

    gl_FragColor = vec4(color, opacity);
  }
`;

const dotVertex = /* glsl */ `
  uniform float uPixelRatio;
  uniform float uSize;
  attribute float aScale;
  varying float vFacing;

  void main() {
    vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
    vec3 viewDir = normalize(-mvPosition.xyz);
    vFacing = dot(normalize((modelViewMatrix * vec4(normalize(position), 0.0)).xyz), viewDir);

    gl_PointSize = uSize * aScale * uPixelRatio * (150.0 / -mvPosition.z);
    gl_Position = projectionMatrix * mvPosition;
  }
`;

const dotFragment = /* glsl */ `
  precision highp float;
  uniform vec3 uColor;
  varying float vFacing;

  void main() {
    float d = length(gl_PointCoord - vec2(0.5));
    if (d > 0.4) discard;

    // Front = fully opaque, back = fade out
    float opacity = vFacing > 0.0
      ? 1.0
      : max(0.0, 1.0 + vFacing * 1.5);

    gl_FragColor = vec4(uColor, opacity);
  }
`;

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

const DotLayer = memo(function DotLayer({
  positions,
  scales,
  color,
  size,
}: {
  positions: Float32Array;
  scales: Float32Array;
  color: string;
  size: number;
}) {
  const { gl, size: viewportSize } = useThree();
  const materialRef = useRef<THREE.ShaderMaterial>(null!);

  // Scale dots to appear consistent across screen sizes
  // Use the smaller dimension so dots fit both narrow and short screens
  const responsiveSize = useMemo(() => {
    const refSize = 900; // reference: dots tuned for ~900px smallest dimension
    const smallest = Math.min(viewportSize.width, viewportSize.height);
    const scale = Math.max(0.35, Math.min(1.2, smallest / refSize));
    return size * scale;
  }, [size, viewportSize.width, viewportSize.height]);

  const { geometry, uniforms } = useMemo(() => {
    const geo = new THREE.BufferGeometry();
    geo.setAttribute("position", new THREE.BufferAttribute(positions, 3));
    geo.setAttribute("aScale", new THREE.BufferAttribute(scales, 1));

    return {
      geometry: geo,
      uniforms: {
        uColor: { value: new THREE.Color(color) },
        uPixelRatio: { value: gl.getPixelRatio() },
        uSize: { value: responsiveSize },
      },
    };
  }, [positions, scales, color, responsiveSize, gl]);

  // Update size uniform when viewport changes without recreating geometry
  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.uniforms.uSize.value = responsiveSize;
    }
  }, [responsiveSize]);

  useEffect(() => {
    return () => geometry.dispose();
  }, [geometry]);

  return (
    <points geometry={geometry}>
      <shaderMaterial
        ref={materialRef}
        vertexShader={dotVertex}
        fragmentShader={dotFragment}
        uniforms={uniforms}
        transparent
      />
    </points>
  );
});

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export function DottedGlobe({
  dotStep = 1.1,
  radius = 2.5,
  dotColor = "#ede6db",
  dotSize = 0.22,
  waterColor = "#87c1c9",
  waterOpacity = 0.15,
  arcs,
  arcDelay = 0,
  rotationSpeed = 0.1,
  liveCards = [],
}: DottedGlobeProps = {}) {
  const arcData = arcs ?? MOCK_ARCS;
  const groupRef = useRef<THREE.Group>(null!);

  // Landed cards state: stamps that stick to the rotating globe
  const [landedCards, setLandedCards] = useState<
    Array<{
      id: string;
      frontImageUrl: string;
      latitude: number;
      longitude: number;
      landedAt: number;
    }>
  >([]);

  const handleCardLanded = useCallback((card: LiveCard, clockTime: number) => {
    setLandedCards((prev) => [
      ...prev,
      {
        id: card.id,
        frontImageUrl: card.frontImageUrl,
        latitude: card.latitude,
        longitude: card.longitude,
        landedAt: clockTime,
      },
    ]);
  }, []);

  const handleStampExpired = useCallback((id: string) => {
    setLandedCards((prev) => prev.filter((c) => c.id !== id));
  }, []);

  const landData = useMemo(() => computeLandDots(dotStep, radius), [dotStep, radius]);

  // Set initial rotation so Belgium (lng ~4°) faces the camera
  const initialRotation = useRef((180 - 4 + 40) * DEG);

  useFrame((_, delta) => {
    groupRef.current.rotation.y += delta * rotationSpeed;
  });

  return (
    <>
      <group rotation={[0, 0, -11.7 * DEG]}>
        <group ref={groupRef} rotation={[0, initialRotation.current, 0]}>
          <mesh>
            <sphereGeometry args={[radius * 0.99, 64, 64]} />
            <shaderMaterial
              vertexShader={oceanSphereVertex}
              fragmentShader={oceanSphereFragment}
              uniforms={{
                uMask: { value: MASK_TEXTURE },
                uWaterColor: { value: new THREE.Color(waterColor) },
                uLandColor: { value: new THREE.Color("#000000") },
                uWaterOpacity: { value: waterOpacity },
                uLandOpacity: { value: 0.4 },
              }}
              transparent
              depthWrite={false}
            />
          </mesh>
          <DotLayer
            positions={landData.positions}
            scales={landData.scales}
            color={dotColor}
            size={dotSize}
          />
          {arcData.length > 0 && <ArcLayer arcs={arcData} radius={radius} delay={arcDelay} />}

          {/* Landed card stamps — inside rotating group so they stick to the globe */}
          {landedCards.map((card) => (
            <LandedCardStamp
              key={`landed-${card.id}`}
              latitude={card.latitude}
              longitude={card.longitude}
              radius={radius}
              frontImageUrl={card.frontImageUrl}
              landedAt={card.landedAt}
              onExpired={() => handleStampExpired(card.id)}
            />
          ))}
        </group>
      </group>

      {/* Flying cards — fully outside tilt group, in scene/world space */}
      {liveCards.length > 0 && (
        <PostcardFlightLayer cards={liveCards} radius={radius} onCardLanded={handleCardLanded} />
      )}
    </>
  );
}
