import { useRef, useMemo, useEffect, memo } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'
import { LAND_MASK_B64, MASK_W, MASK_H } from './land-mask'
import { DOT_STEP, DOT_RADIUS, POSITIONS_B64, SCALES_B64, DOT_COUNT } from './land-dots'
import { latLngToVec3 } from './geo'
import { ArcLayer } from './ArcLayer'
import type { ArcTarget } from './types'

export interface DottedGlobeProps {
  /** Spacing between land dots in degrees (default: 1.1) */
  dotStep?: number
  /** Globe radius (default: 2.5) */
  radius?: number
  /** Land dot color (default: '#ede6db') */
  dotColor?: string
  /** Land dot size multiplier (default: 0.45) */
  dotSize?: number
  /** Water/ocean color (default: '#4a7fb5') */
  waterColor?: string
  /** Water opacity (default: 0.12) */
  waterOpacity?: number
  /** Postcard arc destinations */
  arcs?: ArcTarget[]
  /** Auto-rotation speed in rad/s (default: 0.1) */
  rotationSpeed?: number
}

// ---------------------------------------------------------------------------
// Mock postcard destinations (used when no arcs prop is provided)
// ---------------------------------------------------------------------------

const MOCK_ARCS: ArcTarget[] = [
  { id: '1', latitude: 35.6762, longitude: 139.6503 },   // Tokyo
  { id: '2', latitude: -33.8688, longitude: 151.2093 },  // Sydney
  { id: '3', latitude: 40.7128, longitude: -74.006 },    // New York
  { id: '4', latitude: -22.9068, longitude: -43.1729 },  // Rio de Janeiro
  { id: '5', latitude: 28.6139, longitude: 77.209 },     // New Delhi
  { id: '6', latitude: 48.8566, longitude: 2.3522 },     // Paris
  { id: '7', latitude: -1.2921, longitude: 36.8219 },    // Nairobi
  { id: '8', latitude: 55.7558, longitude: 37.6173 },    // Moscow
  { id: '9', latitude: 37.5665, longitude: 126.978 },    // Seoul
  { id: '10', latitude: -34.6037, longitude: -58.3816 }, // Buenos Aires
]

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEG = Math.PI / 180

// ---------------------------------------------------------------------------
// Decode land mask once at module level (~1ms)
// ---------------------------------------------------------------------------

const LAND_MASK: Uint8Array = (() => {
  const bin = atob(LAND_MASK_B64)
  const arr = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i)
  return arr
})()

function sampleMask(lat: number, lng: number): boolean {
  const x = Math.floor(((lng + 180) / 360) * MASK_W) % MASK_W
  const y = Math.max(0, Math.min(MASK_H - 1, Math.floor(((90 - lat) / 180) * MASK_H)))
  const idx = y * MASK_W + x
  return (LAND_MASK[idx >> 3] & (1 << (idx & 7))) !== 0
}

// ---------------------------------------------------------------------------
// Precalculated dot data (generated by scripts/generate-land-dots.ts)
// ---------------------------------------------------------------------------

interface LandData {
  positions: Float32Array
  scales: Float32Array
}

function base64ToFloat32(b64: string): Float32Array {
  const bin = atob(b64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return new Float32Array(bytes.buffer)
}

const PRECALC_DOTS: LandData = {
  positions: base64ToFloat32(POSITIONS_B64),
  scales: base64ToFloat32(SCALES_B64),
}

function computeLandDots(step: number, radius: number): LandData {
  if (step === DOT_STEP && radius === DOT_RADIUS) return PRECALC_DOTS

  // Fallback: compute at runtime for non-default params
  const positions: number[] = []
  const scales: number[] = []

  for (let lat = -80 + step / 2; lat < 90; lat += step) {
    const cosLat = Math.cos(lat * DEG)
    const lngStep = cosLat > 0.05 ? step / cosLat : 360

    let scale = 1
    if (lat < -65) scale = Math.max(0.3, (lat + 80) / 15)
    else if (lat > 75) scale = Math.max(0.3, (90 - lat) / 15)

    for (let lng = -180 + lngStep / 2; lng < 180; lng += lngStep) {
      if (sampleMask(lat, lng)) {
        const [x, y, z] = latLngToVec3(lat, lng, radius)
        positions.push(x, y, z)
        scales.push(scale)
      }
    }
  }

  return {
    positions: new Float32Array(positions),
    scales: new Float32Array(scales),
  }
}

// ---------------------------------------------------------------------------
// Land mask as a DataTexture (for the inner sphere shader)
// ---------------------------------------------------------------------------

const MASK_TEXTURE: THREE.DataTexture = (() => {
  const data = new Uint8Array(MASK_W * MASK_H * 4)
  for (let i = 0; i < MASK_W * MASK_H; i++) {
    const isLand = (LAND_MASK[i >> 3] & (1 << (i & 7))) !== 0
    const v = isLand ? 255 : 0
    data[i * 4] = v
    data[i * 4 + 1] = v
    data[i * 4 + 2] = v
    data[i * 4 + 3] = 255
  }
  const tex = new THREE.DataTexture(data, MASK_W, MASK_H, THREE.RGBAFormat)
  tex.needsUpdate = true
  tex.minFilter = THREE.LinearFilter
  tex.magFilter = THREE.LinearFilter
  tex.wrapS = THREE.RepeatWrapping
  return tex
})()

// ---------------------------------------------------------------------------
// Shaders
// ---------------------------------------------------------------------------

const oceanSphereVertex = /* glsl */ `
  varying vec2 vUv;
  varying vec3 vViewPos;
  varying vec3 vNormal;

  void main() {
    vUv = uv;
    vNormal = normalize(normalMatrix * normal);
    vViewPos = (modelViewMatrix * vec4(position, 1.0)).xyz;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`

const oceanSphereFragment = /* glsl */ `
  precision highp float;
  uniform sampler2D uMask;
  uniform vec3 uWaterColor;
  uniform vec3 uLandColor;
  uniform float uWaterOpacity;
  uniform float uLandOpacity;
  varying vec2 vUv;
  varying vec3 vViewPos;
  varying vec3 vNormal;

  void main() {
    // Flip V (mask top-to-bottom, UVs bottom-to-top), mirror U, shift 0.5 to align with dot longitudes
    float land = texture2D(uMask, vec2(fract(1.0 - vUv.x + 0.5), 1.0 - vUv.y)).r;

    // Water = blue, land = dark
    vec3 color = mix(uWaterColor, uLandColor, land);
    float opacity = mix(uWaterOpacity, uLandOpacity, land);

    // Fade backside
    vec3 viewDir = normalize(-vViewPos);
    float facing = dot(vNormal, viewDir);
    if (facing < 0.0) {
      opacity *= max(0.0, 1.0 + facing * 1.5);
    }

    gl_FragColor = vec4(color, opacity);
  }
`

const dotVertex = /* glsl */ `
  uniform float uPixelRatio;
  uniform float uSize;
  attribute float aScale;
  varying float vFacing;

  void main() {
    vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
    vec3 viewDir = normalize(-mvPosition.xyz);
    vFacing = dot(normalize((modelViewMatrix * vec4(normalize(position), 0.0)).xyz), viewDir);

    gl_PointSize = uSize * aScale * uPixelRatio * (150.0 / -mvPosition.z);
    gl_Position = projectionMatrix * mvPosition;
  }
`

const dotFragment = /* glsl */ `
  precision highp float;
  uniform vec3 uColor;
  varying float vFacing;

  void main() {
    float d = length(gl_PointCoord - vec2(0.5));
    if (d > 0.4) discard;

    // Front = fully opaque, back = fade out
    float opacity = vFacing > 0.0
      ? 1.0
      : max(0.0, 1.0 + vFacing * 1.5);

    gl_FragColor = vec4(uColor, opacity);
  }
`

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

const DotLayer = memo(function DotLayer({
  positions,
  scales,
  color,
  size,
}: {
  positions: Float32Array
  scales: Float32Array
  color: string
  size: number
}) {
  const { gl, size: viewportSize } = useThree()
  const materialRef = useRef<THREE.ShaderMaterial>(null!)

  // Scale dots based on viewport width — smaller screens get smaller dots
  const responsiveSize = useMemo(() => {
    const baseWidth = 1200
    const width = viewportSize.width
    const scale = Math.max(0.4, Math.min(1.2, width / baseWidth))
    return size * scale
  }, [size, viewportSize.width])

  const { geometry, uniforms } = useMemo(() => {
    const geo = new THREE.BufferGeometry()
    geo.setAttribute('position', new THREE.BufferAttribute(positions, 3))
    geo.setAttribute('aScale', new THREE.BufferAttribute(scales, 1))

    return {
      geometry: geo,
      uniforms: {
        uColor: { value: new THREE.Color(color) },
        uPixelRatio: { value: gl.getPixelRatio() },
        uSize: { value: responsiveSize },
      },
    }
  }, [positions, scales, color, responsiveSize, gl])

  // Update size uniform when viewport changes without recreating geometry
  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.uniforms.uSize.value = responsiveSize
    }
  }, [responsiveSize])

  useEffect(() => {
    return () => geometry.dispose()
  }, [geometry])

  return (
    <points geometry={geometry}>
      <shaderMaterial
        ref={materialRef}
        vertexShader={dotVertex}
        fragmentShader={dotFragment}
        uniforms={uniforms}
        transparent
      />
    </points>
  )
})

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export function DottedGlobe({
  dotStep = 1.1,
  radius = 2.5,
  dotColor = '#ede6db',
  dotSize = 0.45,
  waterColor = '#87c1c9',
  waterOpacity = 0.15,
  arcs,
  rotationSpeed = 0.1,
}: DottedGlobeProps = {}) {
  const arcData = arcs ?? MOCK_ARCS
  const groupRef = useRef<THREE.Group>(null!)

  const landData = useMemo(
    () => computeLandDots(dotStep, radius),
    [dotStep, radius],
  )

  useFrame((_, delta) => {
    groupRef.current.rotation.y += delta * rotationSpeed
  })

  return (
    <group rotation={[0, 0, -11.7 * DEG]}>
      <group ref={groupRef}>
        <mesh>
          <sphereGeometry args={[radius * 0.99, 64, 64]} />
          <shaderMaterial
            vertexShader={oceanSphereVertex}
            fragmentShader={oceanSphereFragment}
            uniforms={{
              uMask: { value: MASK_TEXTURE },
              uWaterColor: { value: new THREE.Color(waterColor) },
              uLandColor: { value: new THREE.Color('#000000') },
              uWaterOpacity: { value: waterOpacity },
              uLandOpacity: { value: 0.4 },
            }}
            transparent
            depthWrite={false}
          />
        </mesh>
        <DotLayer positions={landData.positions} scales={landData.scales} color={dotColor} size={dotSize} />
        {arcData.length > 0 && <ArcLayer arcs={arcData} radius={radius} />}
      </group>
    </group>
  )
}
