import { useRef, useMemo, useEffect, useState, useCallback, memo } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import { DataTexture, RGBAFormat, LinearFilter, RepeatWrapping, Color, BufferGeometry, BufferAttribute } from "three";
import type { Group, ShaderMaterial } from "three";
import { LAND_MASK_B64, MASK_W, MASK_H } from "./land-mask";
import { DOT_STEP, DOTS_B64 } from "./land-dots";
import { latLngToVec3 } from "./geo";
import { ArcLayer } from "./ArcLayer";
import { PostcardFlightLayer } from "./PostcardFlightLayer";
import type { StampHoverData } from "./PostcardFlightLayer";
import { InstancedStamps } from "./InstancedStamps";
import type { ArcTarget, LiveCard } from "./types";

export interface DottedGlobeProps {
  /** Spacing between land dots in degrees (default: 1.1) */
  dotStep?: number;
  /** Globe radius (default: 2.5) */
  radius?: number;
  /** Land dot color (default: '#ede6db') */
  dotColor?: string;
  /** Land dot size multiplier (default: 0.45) */
  dotSize?: number;
  /** Water/ocean color (default: '#4a7fb5') */
  waterColor?: string;
  /** Water opacity (default: 0.12) */
  waterOpacity?: number;
  /** Postcard arc destinations */
  arcs?: ArcTarget[];
  /** Delay in seconds before arcs start animating (default: 0) */
  arcDelay?: number;
  /** Auto-rotation speed in rad/s (default: 0.1) */
  rotationSpeed?: number;
  /** Live postcard cards to animate flying toward the globe */
  liveCards?: LiveCard[];
  /** Pre-existing postcards from the database — rendered as permanent stamps */
  persistentCards?: LiveCard[];
  /** Called on stamp hover (preview) */
  onCardHover?: (data: StampHoverData | null) => void;
  /** Called on stamp click (pin) */
  onCardSelect?: (data: StampHoverData | null) => void;
  /** Called when a live card finishes its flight animation */
  onCardLanded?: (card: LiveCard, clockTime: number) => void;
  /** Pause globe rotation (e.g. when a card is focused) */
  paused?: boolean;
}

// ---------------------------------------------------------------------------
// Mock postcard destinations (used when no arcs prop is provided)
// ---------------------------------------------------------------------------

const MOCK_ARCS: ArcTarget[] = [
  { id: "1", latitude: 35.6762, longitude: 139.6503 }, // Tokyo
  { id: "2", latitude: -33.8688, longitude: 151.2093 }, // Sydney
  { id: "3", latitude: 40.7128, longitude: -74.006 }, // New York
  { id: "4", latitude: -22.9068, longitude: -43.1729 }, // Rio de Janeiro
  { id: "5", latitude: 28.6139, longitude: 77.209 }, // New Delhi
  { id: "6", latitude: 48.8566, longitude: 2.3522 }, // Paris
  { id: "7", latitude: -1.2921, longitude: 36.8219 }, // Nairobi
  { id: "8", latitude: 55.7558, longitude: 37.6173 }, // Moscow
  { id: "9", latitude: 37.5665, longitude: 126.978 }, // Seoul
  { id: "10", latitude: -34.6037, longitude: -58.3816 }, // Buenos Aires
];

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEG = Math.PI / 180;

// ---------------------------------------------------------------------------
// Decode land mask once at module level (~1ms)
// ---------------------------------------------------------------------------

const LAND_MASK: Uint8Array = (() => {
  const bin = atob(LAND_MASK_B64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
})();

function sampleMask(lat: number, lng: number): boolean {
  const x = Math.floor(((lng + 180) / 360) * MASK_W) % MASK_W;
  const y = Math.max(0, Math.min(MASK_H - 1, Math.floor(((90 - lat) / 180) * MASK_H)));
  const idx = y * MASK_W + x;
  return (LAND_MASK[idx >> 3] & (1 << (idx & 7))) !== 0;
}

// ---------------------------------------------------------------------------
// Precalculated dot data (generated by scripts/generate-land-dots.ts)
// Stored as Int16 lat/lng pairs, decoded to xyz + scale at load time
// ---------------------------------------------------------------------------

interface LandData {
  positions: Float32Array;
  scales: Float32Array;
}

function scaleForLat(lat: number): number {
  if (lat < -65) return Math.max(0.3, (lat + 80) / 15);
  if (lat > 75) return Math.max(0.3, (90 - lat) / 15);
  return 1;
}

function decodePrecalcDots(radius: number): LandData {
  const bin = atob(DOTS_B64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  const packed = new Int16Array(bytes.buffer);

  const count = packed.length / 2;
  const positions = new Float32Array(count * 3);
  const scales = new Float32Array(count);

  for (let i = 0; i < count; i++) {
    const lat = packed[i * 2] / 100;
    const lng = packed[i * 2 + 1] / 100;
    const [x, y, z] = latLngToVec3(lat, lng, radius);
    positions[i * 3] = x;
    positions[i * 3 + 1] = y;
    positions[i * 3 + 2] = z;
    scales[i] = scaleForLat(lat);
  }

  return { positions, scales };
}

function computeLandDots(step: number, radius: number): LandData {
  // Use precalculated lat/lng data for default step
  if (step === DOT_STEP) return decodePrecalcDots(radius);

  // Fallback: compute at runtime for non-default step
  const positions: number[] = [];
  const scales: number[] = [];

  for (let lat = -80 + step / 2; lat < 90; lat += step) {
    const cosLat = Math.cos(lat * DEG);
    const lngStep = cosLat > 0.05 ? step / cosLat : 360;
    const scale = scaleForLat(lat);

    for (let lng = -180 + lngStep / 2; lng < 180; lng += lngStep) {
      if (sampleMask(lat, lng)) {
        const [x, y, z] = latLngToVec3(lat, lng, radius);
        positions.push(x, y, z);
        scales.push(scale);
      }
    }
  }

  return {
    positions: new Float32Array(positions),
    scales: new Float32Array(scales),
  };
}

// ---------------------------------------------------------------------------
// Land mask as a DataTexture (for the inner sphere shader)
// ---------------------------------------------------------------------------

const MASK_TEXTURE: DataTexture = (() => {
  const data = new Uint8Array(MASK_W * MASK_H * 4);
  for (let i = 0; i < MASK_W * MASK_H; i++) {
    const isLand = (LAND_MASK[i >> 3] & (1 << (i & 7))) !== 0;
    const v = isLand ? 255 : 0;
    data[i * 4] = v;
    data[i * 4 + 1] = v;
    data[i * 4 + 2] = v;
    data[i * 4 + 3] = 255;
  }
  const tex = new DataTexture(data, MASK_W, MASK_H, RGBAFormat);
  tex.needsUpdate = true;
  tex.minFilter = LinearFilter;
  tex.magFilter = LinearFilter;
  tex.wrapS = RepeatWrapping;
  return tex;
})();

// ---------------------------------------------------------------------------
// Shaders
// ---------------------------------------------------------------------------

const oceanSphereVertex = /* glsl */ `
  varying vec2 vUv;
  varying vec3 vViewPos;
  varying vec3 vNormal;

  void main() {
    vUv = uv;
    vNormal = normalize(normalMatrix * normal);
    vViewPos = (modelViewMatrix * vec4(position, 1.0)).xyz;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const oceanSphereFragment = /* glsl */ `
  precision highp float;
  uniform sampler2D uMask;
  uniform vec3 uWaterColor;
  uniform vec3 uLandColor;
  uniform float uWaterOpacity;
  uniform float uLandOpacity;
  varying vec2 vUv;
  varying vec3 vViewPos;
  varying vec3 vNormal;

  void main() {
    // Flip V (mask top-to-bottom, UVs bottom-to-top), mirror U, shift 0.5 to align with dot longitudes
    float land = texture2D(uMask, vec2(vUv.x, 1.0 - vUv.y)).r;

    // Water = blue, land = dark
    vec3 color = mix(uWaterColor, uLandColor, land);
    float opacity = mix(uWaterOpacity, uLandOpacity, land);

    // Fade backside
    vec3 viewDir = normalize(-vViewPos);
    float facing = dot(vNormal, viewDir);
    if (facing < 0.0) {
      opacity *= max(0.0, 1.0 + facing * 1.5);
    }

    gl_FragColor = vec4(color, opacity);
  }
`;

const dotVertex = /* glsl */ `
  uniform float uPixelRatio;
  uniform float uSize;
  attribute float aScale;
  varying float vFacing;

  void main() {
    vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
    vec3 viewDir = normalize(-mvPosition.xyz);
    vFacing = dot(normalize((modelViewMatrix * vec4(normalize(position), 0.0)).xyz), viewDir);

    gl_PointSize = uSize * aScale * uPixelRatio * (150.0 / -mvPosition.z);
    gl_Position = projectionMatrix * mvPosition;
  }
`;

const dotFragment = /* glsl */ `
  precision highp float;
  uniform vec3 uColor;
  varying float vFacing;

  void main() {
    float d = length(gl_PointCoord - vec2(0.5));
    if (d > 0.4) discard;

    // Front = fully opaque, back = fade out
    float opacity = vFacing > 0.0
      ? 1.0
      : max(0.0, 1.0 + vFacing * 1.5);

    gl_FragColor = vec4(uColor, opacity);
  }
`;

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

const DotLayer = memo(function DotLayer({
  positions,
  scales,
  color,
  size,
}: {
  positions: Float32Array;
  scales: Float32Array;
  color: string;
  size: number;
}) {
  const { gl, size: viewportSize } = useThree();
  const materialRef = useRef<ShaderMaterial>(null!);

  // Scale dots to appear consistent across screen sizes
  // Use the smaller dimension so dots fit both narrow and short screens
  const responsiveSize = useMemo(() => {
    const refSize = 900; // reference: dots tuned for ~900px smallest dimension
    const smallest = Math.min(viewportSize.width, viewportSize.height);
    const scale = Math.max(0.35, Math.min(1.2, smallest / refSize));
    return size * scale;
  }, [size, viewportSize.width, viewportSize.height]);

  const geometry = useMemo(() => {
    const geo = new BufferGeometry();
    geo.setAttribute("position", new BufferAttribute(positions, 3));
    geo.setAttribute("aScale", new BufferAttribute(scales, 1));
    return geo;
  }, [positions, scales]);

  const uniforms = useMemo(() => ({
    uColor: { value: new Color(color) },
    uPixelRatio: { value: 1 },
    uSize: { value: size },
  }), [color, size]);

  // Update dynamic uniforms without recreating geometry or material
  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.uniforms.uSize.value = responsiveSize;
      materialRef.current.uniforms.uPixelRatio.value = gl.getPixelRatio();
    }
  }, [responsiveSize, gl]);

  useEffect(() => {
    return () => geometry.dispose();
  }, [geometry]);

  return (
    <points geometry={geometry}>
      <shaderMaterial
        ref={materialRef}
        vertexShader={dotVertex}
        fragmentShader={dotFragment}
        uniforms={uniforms}
        transparent
      />
    </points>
  );
});

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export const DottedGlobe = memo(function DottedGlobe({
  dotStep = 1.1,
  radius = 2.5,
  dotColor = "#ede6db",
  dotSize = 0.22,
  waterColor = "#87c1c9",
  waterOpacity = 0.15,
  arcs,
  arcDelay = 0,
  rotationSpeed = 0.1,
  liveCards = [],
  persistentCards = [],
  onCardHover,
  onCardSelect,
  onCardLanded: onCardLandedProp,
  paused = false,
}: DottedGlobeProps = {}) {
  const arcData = arcs ?? MOCK_ARCS;
  const groupRef = useRef<Group>(null!);

  // Keep paused and callback in refs so event listeners always see the latest value
  const pausedRef = useRef(paused);
  pausedRef.current = paused;
  const onCardLandedRef = useRef(onCardLandedProp);
  onCardLandedRef.current = onCardLandedProp;

  // --- Drag-to-rotate state ---
  const isDragging = useRef(false);
  const dragStartX = useRef(0);
  const dragStartY = useRef(0);
  const rotationAtDragStart = useRef(0);
  const tiltAtDragStart = useRef(0);
  const userTilt = useRef(0);
  const idleTime = useRef(Infinity);
  const autoRotateBlend = useRef(1); // 1 = full auto, 0 = user control
  const RESUME_DELAY = 1;
  const DRAG_SENSITIVITY = 0.005;

  const { gl } = useThree();

  // Attach drag listeners to the R3F event target (the container div that
  // wraps the canvas). R3F listens on this element, so we use capture phase
  // to fire before R3F processes the event. Move/up on window so dragging
  // continues outside the canvas bounds.
  useEffect(() => {
    const canvas = gl.domElement;
    // R3F attaches its pointer listeners to the canvas's parent div
    const target = canvas.parentElement ?? canvas;

    const onPointerDown = (e: PointerEvent) => {
      if (pausedRef.current) return;
      isDragging.current = true;
      dragStartX.current = e.clientX;
      dragStartY.current = e.clientY;
      rotationAtDragStart.current = groupRef.current.rotation.y;
      tiltAtDragStart.current = userTilt.current;
      autoRotateBlend.current = 0;
      idleTime.current = 0;
      canvas.style.cursor = "grabbing";
    };

    const onPointerMove = (e: PointerEvent) => {
      if (!isDragging.current) return;
      const dx = e.clientX - dragStartX.current;
      const dy = e.clientY - dragStartY.current;
      groupRef.current.rotation.y = rotationAtDragStart.current + dx * DRAG_SENSITIVITY;
      userTilt.current = Math.max(-1.4, Math.min(1.4, tiltAtDragStart.current + dy * DRAG_SENSITIVITY * 0.5));
      idleTime.current = 0;
      autoRotateBlend.current = 0;
    };

    const onPointerUp = () => {
      if (isDragging.current) {
        isDragging.current = false;
        idleTime.current = 0;
        canvas.style.cursor = "";
      }
    };

    target.addEventListener("pointerdown", onPointerDown, { capture: true });
    window.addEventListener("pointermove", onPointerMove);
    window.addEventListener("pointerup", onPointerUp);

    return () => {
      target.removeEventListener("pointerdown", onPointerDown, { capture: true });
      window.removeEventListener("pointermove", onPointerMove);
      window.removeEventListener("pointerup", onPointerUp);
    };
  }, [gl]);

  // Landed cards state: stamps that stick to the rotating globe
  const [landedCards, setLandedCards] = useState<
    Array<{
      id: string;
      frontImageUrl: string;
      latitude: number;
      longitude: number;
      senderName?: string;
      message?: string;
      country?: string;
      landedAt: number;
    }>
  >([]);

  // Animate a small subset of persistent cards in via flight on first load only;
  // subsequent batches go straight to stamps without flight animation.
  const MAX_ANIMATED = 10;

  const [stagedFlights, setStagedFlights] = useState<LiveCard[]>([]);
  const [animatingIds, setAnimatingIds] = useState<Set<string>>(new Set());
  const [streamedCards, setStreamedCards] = useState<LiveCard[]>([]);
  const stagedIdsRef = useRef<Set<string>>(new Set());
  const initialFlightsDone = useRef(false);
  const flightTimers = useRef<ReturnType<typeof setTimeout>[]>([]);

  // Cleanup flight timers on unmount only
  useEffect(() => {
    return () => flightTimers.current.forEach(clearTimeout);
  }, []);

  useEffect(() => {
    // Prune stale IDs from previous persistentCards that are no longer present
    const currentIds = new Set(persistentCards.map((c) => c.id));
    for (const id of stagedIdsRef.current) {
      if (!currentIds.has(id)) stagedIdsRef.current.delete(id);
    }
    setStreamedCards((prev) => {
      const next = prev.filter((c) => currentIds.has(c.id));
      return next.length === prev.length ? prev : next;
    });

    const newCards = persistentCards.filter((c) => !stagedIdsRef.current.has(c.id));
    if (newCards.length === 0) return;

    for (const c of newCards) stagedIdsRef.current.add(c.id);

    // Only animate flights for the very first batch
    if (!initialFlightsDone.current) {
      initialFlightsDone.current = true;

      const toAnimate = newCards.slice(0, MAX_ANIMATED);
      const animIds = new Set(toAnimate.map((c) => c.id));
      setAnimatingIds(animIds);

      setStagedFlights(toAnimate);

      // Rest of first batch goes straight to stamps
      const rest = newCards.filter((c) => !animIds.has(c.id));
      if (rest.length > 0) {
        setStreamedCards((prev) => [...prev, ...rest]);
      }
    } else {
      // Subsequent batches: add directly to stamps, no flight animation
      setStreamedCards((prev) => [...prev, ...newCards]);
    }
  }, [persistentCards]);

  const handlePersistentLanded = useCallback((_card: LiveCard) => {
    setAnimatingIds((prev) => {
      const next = new Set(prev);
      next.delete(_card.id);
      return next;
    });
    setStagedFlights((prev) => prev.filter((c) => c.id !== _card.id));
    // Add to streamedCards so the card appears as a stamp after flight
    setStreamedCards((prev) => [...prev, _card]);
  }, []);

  const handleCardLanded = useCallback((card: LiveCard, clockTime: number) => {
    setLandedCards((prev) => [
      ...prev,
      {
        id: card.id,
        frontImageUrl: card.frontImageUrl,
        latitude: card.latitude,
        longitude: card.longitude,
        senderName: card.senderName,
        message: card.message,
        country: card.country,
        landedAt: clockTime,
      },
    ]);
    onCardLandedRef.current?.(card, clockTime);
  }, []);

  const handleStampExpired = useCallback((id: string) => {
    setLandedCards((prev) => prev.filter((c) => c.id !== id));
  }, []);

  const landData = useMemo(() => computeLandDots(dotStep, radius), [dotStep, radius]);

  // Set initial rotation so Belgium (lng ~4°) faces the camera
  const initialRotation = useRef((180 - 4 + 40) * DEG);

  // Memoize ocean uniforms to avoid recreating on every render
  const oceanUniforms = useMemo(() => ({
    uMask: { value: MASK_TEXTURE },
    uWaterColor: { value: new Color(waterColor) },
    uLandColor: { value: new Color("#000000") },
    uWaterOpacity: { value: waterOpacity },
    uLandOpacity: { value: 0.4 },
  }), [waterColor, waterOpacity]);

  // Memoize filtered persistent cards to prevent unnecessary slot resyncs
  const visiblePersistentCards = useMemo(
    () => streamedCards.filter((c) => !animatingIds.has(c.id)),
    [streamedCards, animatingIds],
  );

  const tiltGroupRef = useRef<Group>(null!);

  // Single useFrame for rotation + tilt (uses pausedRef to avoid stale closures)
  useFrame((_, rawDelta) => {
    // Clamp delta to avoid a huge spin after returning from a background tab
    const delta = Math.min(rawDelta, 0.1);

    // Track idle time using frame deltas
    if (isDragging.current) {
      idleTime.current = 0;
    } else {
      idleTime.current += delta;
    }

    const isPaused = pausedRef.current;

    // Smoothly blend back to auto-rotation after drag ends (not while paused)
    if (!isPaused && !isDragging.current && idleTime.current > RESUME_DELAY) {
      autoRotateBlend.current = Math.min(1, autoRotateBlend.current + delta * 0.8);
    }

    // Auto-rotate when not paused and not being dragged
    if (!isPaused && !isDragging.current && autoRotateBlend.current > 0) {
      groupRef.current.rotation.y += delta * rotationSpeed * autoRotateBlend.current;
    }

    // Ease vertical tilt back to 0 when auto-rotating (not while paused)
    if (!isPaused && autoRotateBlend.current > 0.5 && !isDragging.current) {
      userTilt.current *= 1 - delta * 2;
    }

    // Apply user tilt
    if (tiltGroupRef.current) {
      tiltGroupRef.current.rotation.x = userTilt.current;
    }
  });

  return (
    <>
      <group rotation={[0, 0, -11.7 * DEG]}>
        <group ref={tiltGroupRef}>
        <group ref={groupRef} rotation={[0, initialRotation.current, 0]}>
          <mesh raycast={() => null}>
            <sphereGeometry args={[radius * 0.99, 64, 64]} />
            <shaderMaterial
              vertexShader={oceanSphereVertex}
              fragmentShader={oceanSphereFragment}
              uniforms={oceanUniforms}
              transparent
              depthWrite={false}
            />
          </mesh>
          <DotLayer
            positions={landData.positions}
            scales={landData.scales}
            color={dotColor}
            size={dotSize}
          />
          {arcData.length > 0 && <ArcLayer arcs={arcData} radius={radius} delay={arcDelay} />}

          {/* All stamps — instanced for performance (single draw call) */}
          <InstancedStamps
            persistentCards={visiblePersistentCards}
            landedCards={landedCards}
            radius={radius}
            onHover={onCardHover}
            onSelect={onCardSelect}
            onLandedExpired={handleStampExpired}
          />
        </group>
        </group>
      </group>

      {/* Flying cards — fully outside tilt group, in scene/world space */}
      {liveCards.length > 0 && (
        <PostcardFlightLayer cards={liveCards} radius={radius} onCardLanded={handleCardLanded} />
      )}

      {/* Persistent cards animating in via flight */}
      {stagedFlights.length > 0 && (
        <PostcardFlightLayer cards={stagedFlights} radius={radius} onCardLanded={handlePersistentLanded} />
      )}
    </>
  );
});
