/**
 * Pre-computes land dot lat/lng pairs for the default dotStep (1.1),
 * quantized to Int16 for minimal file size. Scales are derived from
 * latitude at decode time so they don't need to be stored.
 *
 * Encoding: each dot = 2 × Int16 (lat, lng) = 4 bytes
 * Quantization: lat × 100 → Int16, lng × 100 → Int16 (0.01° precision)
 *
 * Run: bun packages/shared/scripts/generate-land-dots.ts
 */

import { LAND_MASK_B64, MASK_W, MASK_H } from "../src/land-mask";

const DEG = Math.PI / 180;
const STEP = 1.1;

// Decode land mask
const bin = atob(LAND_MASK_B64);
const LAND_MASK = new Uint8Array(bin.length);
for (let i = 0; i < bin.length; i++) LAND_MASK[i] = bin.charCodeAt(i);

function sampleMask(lat: number, lng: number): boolean {
  const x = Math.floor(((lng + 180) / 360) * MASK_W) % MASK_W;
  const y = Math.max(0, Math.min(MASK_H - 1, Math.floor(((90 - lat) / 180) * MASK_H)));
  const idx = y * MASK_W + x;
  return (LAND_MASK[idx >> 3] & (1 << (idx & 7))) !== 0;
}

const lats: number[] = [];
const lngs: number[] = [];

for (let lat = -80 + STEP / 2; lat < 90; lat += STEP) {
  const cosLat = Math.cos(lat * DEG);
  const lngStep = cosLat > 0.05 ? STEP / cosLat : 360;

  for (let lng = -180 + lngStep / 2; lng < 180; lng += lngStep) {
    if (sampleMask(lat, lng)) {
      lats.push(lat);
      lngs.push(lng);
    }
  }
}

// Pack as interleaved Int16 pairs: [lat0, lng0, lat1, lng1, ...]
const packed = new Int16Array(lats.length * 2);
for (let i = 0; i < lats.length; i++) {
  packed[i * 2] = Math.round(lats[i] * 100);
  packed[i * 2 + 1] = Math.round(lngs[i] * 100);
}

const bytes = new Uint8Array(packed.buffer);
let binary = "";
for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
const b64 = btoa(binary);

const output = `// Auto-generated by scripts/generate-land-dots.ts — do not edit
// ${lats.length} dots, ${packed.byteLength} bytes (${b64.length} chars b64)
// Encoding: Int16 pairs [lat×100, lng×100] — decode with decodeLandDots()

export const DOT_STEP = ${STEP}
export const DOT_COUNT = ${lats.length}

export const DOTS_B64 = '${b64}'
`;

const path = new URL("../src/land-dots.ts", import.meta.url).pathname;
await Bun.write(path, output);

console.log(`Wrote ${lats.length} dots to src/land-dots.ts`);
console.log(`  packed: ${packed.byteLength} bytes (${b64.length} chars b64)`);
console.log(`  old:    ${lats.length * 16} bytes (positions + scales as Float32)`);
console.log(`  saving: ${Math.round((1 - packed.byteLength / (lats.length * 16)) * 100)}%`);
