/**
 * Build-time script: generates a bit-packed land mask from world-atlas topology.
 * Run: npx tsx scripts/generate-land-mask.ts
 * Output: src/land-mask.ts
 */

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { feature } from 'topojson-client'

const COUNTRIES_URL = 'https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json'
const MASK_W = 360
const MASK_H = 180

// ---------------------------------------------------------------------------
// Point-in-polygon (same logic as DottedGlobe.tsx)
// ---------------------------------------------------------------------------

function rayCast(lng: number, lat: number, ring: number[][]): boolean {
  let inside = false
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1]
    const xj = ring[j][0], yj = ring[j][1]
    if (
      yi > lat !== yj > lat &&
      lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi
    ) {
      inside = !inside
    }
  }
  return inside
}

function pointInRing(lng: number, lat: number, ring: number[][]): boolean {
  let crosses = false
  for (let i = 0; i < ring.length - 1; i++) {
    if (Math.abs(ring[i][0] - ring[i + 1][0]) > 180) {
      crosses = true
      break
    }
  }

  if (crosses) {
    const sLng = lng < 0 ? lng + 360 : lng
    const sRing = ring.map(([x, y]) => [x < 0 ? x + 360 : x, y])
    return rayCast(sLng, lat, sRing)
  }

  return rayCast(lng, lat, ring)
}

function isLand(lng: number, lat: number, geometry: { type: string; coordinates: any }): boolean {
  if (geometry.type === 'Polygon') {
    return pointInRing(lng, lat, geometry.coordinates[0])
  }
  if (geometry.type === 'MultiPolygon') {
    return geometry.coordinates.some(
      (poly: number[][][]) => pointInRing(lng, lat, poly[0]),
    )
  }
  return false
}

function collectGeometries(geojson: any): any[] {
  if (geojson.type === 'FeatureCollection') {
    return geojson.features.flatMap((f: any) => collectGeometries(f))
  }
  if (geojson.type === 'Feature') {
    return geojson.geometry ? [geojson.geometry] : []
  }
  if (geojson.type === 'GeometryCollection') {
    return geojson.geometries ?? []
  }
  return [geojson]
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log('Fetching countries topology...')
  const res = await fetch(COUNTRIES_URL)
  const topology = await res.json()
  const countries = feature(topology, topology.objects.countries)
  const geometries = collectGeometries(countries)
  console.log(`  ${geometries.length} geometries loaded`)

  console.log(`Building ${MASK_W}×${MASK_H} land mask...`)
  const mask = new Uint8Array(MASK_W * MASK_H)
  let landCells = 0

  for (let y = 0; y < MASK_H; y++) {
    const lat = 89.5 - y
    for (let x = 0; x < MASK_W; x++) {
      const lng = -179.5 + x
      if (geometries.some((g: any) => isLand(lng, lat, g))) {
        mask[y * MASK_W + x] = 1
        landCells++
      }
    }
  }
  console.log(`  ${landCells} land cells / ${MASK_W * MASK_H} total`)

  // Bit-pack: 8 cells per byte
  const packed = new Uint8Array(Math.ceil(mask.length / 8))
  for (let i = 0; i < mask.length; i++) {
    if (mask[i]) packed[i >> 3] |= 1 << (i & 7)
  }

  // Base64 encode
  const b64 = Buffer.from(packed).toString('base64')
  console.log(`  Packed: ${packed.length} bytes, base64: ${b64.length} chars`)

  // Write output
  const __dirname = dirname(fileURLToPath(import.meta.url))
  const outPath = resolve(__dirname, '..', 'src', 'land-mask.ts')

  writeFileSync(
    outPath,
    `// Auto-generated by scripts/generate-land-mask.ts — do not edit\n` +
    `// ${MASK_W}×${MASK_H} land mask, bit-packed (${packed.length} bytes)\n` +
    `export const LAND_MASK_B64 = '${b64}'\n` +
    `export const MASK_W = ${MASK_W}\n` +
    `export const MASK_H = ${MASK_H}\n`,
  )

  console.log(`Written to ${outPath}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
