/**
 * Pre-computes land dot positions and scales for the default
 * dotStep (1.1) and radius (2.5), writes them as base64-encoded
 * Float32Arrays to src/land-dots.ts.
 *
 * Run: bun packages/shared/scripts/generate-land-dots.ts
 */

import { LAND_MASK_B64, MASK_W, MASK_H } from '../src/land-mask'

const DEG = Math.PI / 180
const STEP = 1.1
const RADIUS = 2.5

// Decode land mask
const bin = atob(LAND_MASK_B64)
const LAND_MASK = new Uint8Array(bin.length)
for (let i = 0; i < bin.length; i++) LAND_MASK[i] = bin.charCodeAt(i)

function sampleMask(lat: number, lng: number): boolean {
  const x = Math.floor(((lng + 180) / 360) * MASK_W) % MASK_W
  const y = Math.max(0, Math.min(MASK_H - 1, Math.floor(((90 - lat) / 180) * MASK_H)))
  const idx = y * MASK_W + x
  return (LAND_MASK[idx >> 3] & (1 << (idx & 7))) !== 0
}

function latLngToVec3(lat: number, lng: number, r: number): [number, number, number] {
  const phi = (90 - lat) * DEG
  const theta = (180 + lng) * DEG
  return [
    r * Math.sin(phi) * Math.cos(theta),
    r * Math.cos(phi),
    r * Math.sin(phi) * Math.sin(theta),
  ]
}

const positions: number[] = []
const scales: number[] = []

for (let lat = -80 + STEP / 2; lat < 90; lat += STEP) {
  const cosLat = Math.cos(lat * DEG)
  const lngStep = cosLat > 0.05 ? STEP / cosLat : 360

  let scale = 1
  if (lat < -65) scale = Math.max(0.3, (lat + 80) / 15)
  else if (lat > 75) scale = Math.max(0.3, (90 - lat) / 15)

  for (let lng = -180 + lngStep / 2; lng < 180; lng += lngStep) {
    if (sampleMask(lat, lng)) {
      const [x, y, z] = latLngToVec3(lat, lng, RADIUS)
      positions.push(x, y, z)
      scales.push(scale)
    }
  }
}

const posF32 = new Float32Array(positions)
const scaleF32 = new Float32Array(scales)

function float32ToBase64(arr: Float32Array): string {
  const bytes = new Uint8Array(arr.buffer)
  let binary = ''
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i])
  return btoa(binary)
}

const posB64 = float32ToBase64(posF32)
const scaleB64 = float32ToBase64(scaleF32)

const output = `// Auto-generated by scripts/generate-land-dots.ts — do not edit
// Pre-computed for dotStep=${STEP}, radius=${RADIUS}
// ${scales.length} dots, positions: ${posF32.byteLength} bytes, scales: ${scaleF32.byteLength} bytes

export const DOT_STEP = ${STEP}
export const DOT_RADIUS = ${RADIUS}
export const DOT_COUNT = ${scales.length}

export const POSITIONS_B64 = '${posB64}'
export const SCALES_B64 = '${scaleB64}'
`

const path = new URL('../src/land-dots.ts', import.meta.url).pathname
await Bun.write(path, output)

console.log(`Wrote ${scales.length} dots to src/land-dots.ts`)
console.log(`  positions: ${posF32.byteLength} bytes (${posB64.length} chars b64)`)
console.log(`  scales:    ${scaleF32.byteLength} bytes (${scaleB64.length} chars b64)`)
